// src/EmployeeList/client/src/components/employees/EmployeeDetails.vue
<template>
  <div>
    <div class="well">
      <div class="row">
        <div class="col-md-3">
          <strong>Employee Name:</strong>
        </div>
        <div class="col-md-3">
          {{ employee.name }}
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <strong>Employee Email:</strong>
        </div>
        <div class="col-md-3">
          {{ employee.email }}
        </div>
      </div>
    </div>
 
    <div class="row">
      <div class="col-md-12">
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Start Date</th>
                <th>Position</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>{{ employee.startDate }}</td>
                <td>{{ employee.position }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import EmployeeService from '@/services/employee-service'

export default {
    name: 'EmployeeDetails',
    data () {
        return {
            employee: {}
        }
    },
    created () {
      EmployeeService.getSingle(this.$router.currentRoute.params.id)
        .then(response => {
        this.employee = response.data
      })
    }  
}
</script>

<style>
</style>

// src/EmployeeList/ngcleint/src/app/employee/employee-details/employee-details.component.ts
import { Component, OnInit } from '@angular/core';
import { Employee } from 'src/app/_interfaces/employee';
import { Router, ActivatedRoute } from '@angular/router';
import { RepositoryService } from 'src/app/shared/services/repository.service';
import { ErrorHandlerService } from 'src/app/shared/services/error-handler.service';

@Component({
  selector: 'app-employee-details',
  templateUrl: './employee-details.component.html',
  styleUrls: ['./employee-details.component.css']
})
export class EmployeeDetailsComponent implements OnInit {

  public employee: Employee;
  public errorMessage = '';

  constructor(private router: Router, private repo: RepositoryService,
              private route: ActivatedRoute, private errorHandler: ErrorHandlerService) { }

  ngOnInit() {
    this.getEmployeeDetails();
  }

  getEmployeeDetails() {
    const id: string = this.route.snapshot.params.id;
    const apiUrl = `employees/${id}`;

    this.repo.getData(apiUrl).subscribe(res => {
      this.employee = res as Employee;
    },
    (error) => {
      this.errorHandler.handleError(error);
      this.errorMessage = this.errorHandler.errorMessage;
    });
  }

}

<div>
  <div class="well">
    <div class="row">
      <div class="col-md-3">
        <strong>Employee Name:</strong>
      </div>
      <div class="col-md-3">
        {{ employee?.name }}
      </div>
    </div>
    <div class="row">
      <div class="col-md-3">
        <strong>Employee Email:</strong>
      </div>
      <div class="col-md-3">
        {{ employee?.email }}
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Start Date</th>
              <th>Position</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{ employee?.startDate | date: "dd/MM/yyyy" }}</td>
              <td>{{ employee?.position }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
